export interface Game {
  id: string,
  game: string,
  gameVersion: string,
  primaryInInventory: boolean,
  secondaryInInventory: boolean,
  inPromo: string,
  originalPrice: string,
  currentPrice: string,
  primaryValue: string,
  secondaryValue: string,
  rating: string,
  category: string,
  imageLink: string,
  status: string,
}